version: '3.4'

services:
  # MySQL Service
  mysql:
    image: mysql:8.0.33
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quickrectify
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # .NET Core Application
  quickrectify-back:
    build:
      context: ../back
      dockerfile: dot-net.Dockerfile
    ports:
      - "5000:8080"
    environment:
      DOTNET_URLS: "http://+:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  # Angular App
  quickrectify-front:
    build:
      context: ../front
      dockerfile: angular.Dockerfile
    ports:
      - "80:80"  
    depends_on:
      - quickrectify-back  
    restart: unless-stopped

volumes:
  mysql_data:
