worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;

        # Redireciona raiz
        location = / {
            return 301 /quickrectify/;
        }

        # SPA Angular
        location /quickrectify/ {
            root /etc/nginx/html;   # use root em vez de alias
            index index.html;
            try_files $uri $uri/ /quickrectify/index.html;
        }

        # Assets
        location /quickrectify/assets/ {
            root /etc/nginx/html;
            expires 1y;
        }
    }

}
